[package]
name = "rustmongodb"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-cors = "0.6"
mongodb = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"